### ISSUE TITLE
v1.0.1 调用报错

### ISSUE THREAD

**Issue by lorock** [ci-plugins/executeJob#1]
版本:v1.0.1
已按照文档要求配置，流水线调用时报错如下：

[main] WARN com.tencent.bk.devops.atom.task.InnerJobAtom - If permission is required, you can go to BK IAM Center to apply the permission of businessId [4] and hosts related, and you can
 contact business operator or admin to approve applications for you
[main] INFO com.tencent.bk.devops.atom.task.service.JobResourceV3Api - req={"username":"admin","bizId":4,"planId":1000000}
[main] ERROR com.tencent.bk.devops.atom.AtomRunner - Unknown Error：paas.service.consul: Name or service not known
java.net.UnknownHostException: paas.service.consul: Name or service not known
    at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
    at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:929)
    at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1324)
    at java.net.InetAddress.getAllByName0(InetAddress.java:1277)
    at java.net.InetAddress.getAllByName(InetAddress.java:1193)
    at java.net.InetAddress.getAllByName(InetAddress.java:1127)
    at okhttp3.Dns$1.lookup(Dns.java:40)
    at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
    at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
    at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
    at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
    at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
    at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
    at okhttp3.RealCall.execute(RealCall.java:92)
    at com.tencent.bk.devops.atom.task.utils.OkhttpUtils.doHttp(OkhttpUtils.kt:38)
    at com.tencent.bk.devops.atom.task.utils.OkhttpUtils.doHttp(OkhttpUtils.kt:21)
    at com.tencent.bk.devops.atom.task.service.JobResourceV3Api.sendTaskRequest(JobResourceV3Api.kt:89)
    at com.tencent.bk.devops.atom.task.service.JobResourceV3Api.executeJobPlan(JobResourceV3Api.kt:27)
    at com.tencent.bk.devops.atom.task.utils.JobUtils.executeJobPlan(JobUtils.kt:11)
    at com.tencent.bk.devops.atom.task.InnerJobAtom.executeJobPlan(InnerJobAtom.kt:108)
    at com.tencent.bk.devops.atom.task.InnerJobAtom.exceute(InnerJobAtom.kt:58)
    at com.tencent.bk.devops.atom.task.InnerJobAtom.execute(InnerJobAtom.kt:32)
    at com.tencent.bk.devops.atom.AtomRunner.main(AtomRunner.java:29)
[Finish task] status: error, errorType: null, errorCode: null, message: Unknown Error：paas.service.consul: Name or service not known

手动测试ESB地址是可以访问的，详情如下：

# curl -I http://paas.service.consul:80
HTTP/1.1 302 FOUND
Date: Fri, 23 Jul 2021 08:01:46 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Vary: Accept-Language, Cookie
X-Frame-Options: SAMEORIGIN
Location: http://paas.service.consul/login/?c_url=/
Content-Language: zh-hans

**Comment by lorock** [comment]
蓝鲸智云社区版：V6.0.3

**Comment by jsonwan** [comment]
可尝试在蓝盾无编译环境构建机上配置指向paas服务机器的hosts
